### ISSUE TITLE
OSError: Unable to find libfuse

### ISSUE THREAD

**Issue by megapro17** [mxmlnkn/ratarmount#117]
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\megapro17\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts\ratarmount.exe\__main__.py", line 4, in <module>
  File "C:\Users\megapro17\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ratarmount.py", line 24, in <module>
    import fuse
  File "C:\Users\megapro17\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\fuse.py", line 115, in <module>
    raise EnvironmentError('Unable to find libfuse')
OSError: Unable to find libfuse
```

**Comment by mxmlnkn** [comment]
libfuse is a required dependency of ratarmount. You need to install it. On Debian-like systems, you can install it with `sudo apt install fuse`. Unfortunately, I have no idea how to install it on Windows. In WSL, I think you can also install it with `apt install fuse`. Some more information as to how you have installed ratarmount exactly, would be helpful.

**Comment by mxmlnkn** [comment]
I think on a bare Windows installation (without WSL), you have to install [WinFsp](https://winfsp.dev/rel/) for ratarmount to work.
