### ISSUE TITLE
Running on Lustre filesystem

### ISSUE THREAD

**Issue by xiaofanjin** [mxmlnkn/ratarmount#143]
Hi I'm trying to use ratarmount to mount a .tar file on a Lustre file system, but after successfully building the .tar.index.sqlite file, I run into this error:
```
fusermount: mounting over filesystem type 0x0bd00bd0 is forbidden
Traceback (most recent call last):
  File "/home/xiaofanj/.local/lib/python3.11/site-packages/ratarmount.py", line 1803, in cli
    fuse.FUSE(
  File "/home/xiaofanj/.local/lib/python3.11/site-packages/fuse.py", line 711, in __init__
    raise RuntimeError(err)
RuntimeError: 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/xiaofanj/.local/bin/ratarmount", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/xiaofanj/.local/lib/python3.11/site-packages/ratarmount.py", line 1811, in cli
    raise RatarmountError(
ratarmountcore.utils.RatarmountError: FUSE mountpoint could not be created. See previous output for more information.
```
Digging a bit [further](https://github.com/libfuse/libfuse/issues/304), it seems this incompatibility may be buried deeper in a dependency like fusepy / libfuse, but I am not familiar with these tools so am not sure whether a fix would feasible - any insights appreciated thanks!

**Comment by xiaofanjin** [comment]
Thanks, worked!
