### ISSUE TITLE
ModuleNotFoundError: No module named '_sqlite3'

### ISSUE THREAD

**Issue by rngadam** [mxmlnkn/ratarmount#30]
running ratarmount I'm getting this:

```
Traceback (most recent call last):
  File "/venv/bin/ratarmount", line 6, in <module>
    from ratarmount import cli
  File "/venv/lib/python3.8/site-packages/ratarmount.py", line 11, in <module>
    import sqlite3
  File "/usr/local/lib/python3.8/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.8/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
```

the list of packages:

```
$ ./venv/bin/pip list
Package       Version
------------- -------
click         7.1.2
fusepy        3.0.1
indexed-bzip2 1.1.0
indexed-gzip  1.0.0
pip           20.1
pip-tools     5.1.2
pysqlite3     0.4.2
ratarmount    0.4.1
setuptools    41.2.0
six           1.14.0
wheel         0.34.2
```

the list of system packages:

```
$ dpkg -l | grep sqlite3
ii  libsqlite3-0:amd64                   3.22.0-1ubuntu0.3                      amd64        SQLite 3 shared library
ii  libsqlite3-dev:amd64                 3.22.0-1ubuntu0.3                      amd64        SQLite 3 development files
ii  sqlite3                              3.22.0-1ubuntu0.3                      amd64        Command line interface for SQLite 3
```

reinstalling python3.8 or deleting the venv and starting over doesn't help

**Comment by rngadam** [comment]
the problem was a self-built Python 3.8.0 in the PATH (probably not built properly with sqlite3) instead of Python 3.8.2 from the system.

Pointing to the right Python fixed the problem.
