### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by mxmlnkn** [mxmlnkn/ratarmount#35]
When trying to recursively mount ILSVRC2012_train.tar, I get this error at roughly 97% of the file, which is very frustrating. It looks like Python has a recursion depth of 1000, which is funnily enough identical to the 1000 synset classes in ILSVRC2012. It looks like reading the internal tar file does not stop at the end of the tar for some reason. Maybe because `ignore_zeros` is set to True. Looks like the best option would be to use StenciledFile for the internal tar so that an end of file is triggered if tarfile reaches the end. This might lead to some seeking but normally this shouldn't be a problem. Alternatively another different file layer might be introduced, which can work on a streaming file object. Basically only allowing read until a predefined size is met.

```python
Currently at position 144614683136 of 147897477120 (97.78%). Estimated time remaining with current rate: 6 min 50 s, with average rate: 2 min 14 s.
Creating offset dictionary for n09835506.tar ...
Traceback (most recent call last):
  File "/home/user/.local/bin/ratarmount", line 8, in <module>
    sys.exit(cli())
  File "/home/user/.local/lib/python3.8/site-packages/ratarmount.py", line 1557, in cli
    fuseOperationsObject = TarMount(
  File "/home/user/.local/lib/python3.8/site-packages/ratarmount.py", line 995, in __init__
    self.mountSources = [ self._openTar( tarFile, clearIndexCache, recursive, gzipSeekPointSpacing )
  File "/home/user/.local/lib/python3.8/site-packages/ratarmount.py", line 995, in <listcomp>
    self.mountSources = [ self._openTar( tarFile, clearIndexCache, recursive, gzipSeekPointSpacing )
  File "/home/user/.local/lib/python3.8/site-packages/ratarmount.py", line 1039, in _openTar
    return SQLiteIndexedTar( tarFilePath,
  File "/home/user/.local/lib/python3.8/site-packages/ratarmount.py", line 294, in __init__
    self.createIndex( self.tarFileObject )
  File "/home/user/.local/lib/python3.8/site-packages/ratarmount.py", line 447, in createIndex
    self.createIndex( fileObject, progressBar, fullPath, globalOffset if streamed else 0 )
  File "/home/user/.local/lib/python3.8/site-packages/ratarmount.py", line 447, in createIndex
    self.createIndex( fileObject, progressBar, fullPath, globalOffset if streamed else 0 )
  File "/home/user/.local/lib/python3.8/site-packages/ratarmount.py", line 447, in createIndex
    self.createIndex( fileObject, progressBar, fullPath, globalOffset if streamed else 0 )
  [Previous line repeated 979 more times]
  File "/home/user/.local/lib/python3.8/site-packages/ratarmount.py", line 398, in createIndex
    loadedTarFile = tarfile.open( fileobj = fileObject, mode = 'r|' if streamed else 'r:', ignore_zeros = True )
  File "/usr/lib/python3.8/tarfile.py", line 1617, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/usr/lib/python3.8/tarfile.py", line 1647, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/usr/lib/python3.8/tarfile.py", line 1510, in __init__
    self.firstmember = self.next()
  File "/usr/lib/python3.8/tarfile.py", line 2311, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/usr/lib/python3.8/tarfile.py", line 1103, in fromtarfile
    obj = cls.frombuf(buf, tarfile.encoding, tarfile.errors)
  File "/usr/lib/python3.8/tarfile.py", line 1045, in frombuf
    chksum = nti(buf[148:156])
  File "/usr/lib/python3.8/tarfile.py", line 186, in nti
    s = nts(s, "ascii", "strict")
  File "/usr/lib/python3.8/tarfile.py", line 167, in nts
    p = s.find(b"\0")
RecursionError: maximum recursion depth exceeded while calling a Python object
Exception ignored in: <function TarMount.__del__ at 0x7f87deeb75e0>
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/ratarmount.py", line 1036, in __del__
    os.close( self.mountPointFd )
AttributeError: mountPointFd
```

I think, I had other problems with `ignore_zero` and already made it a command line option in my local develop branch.

**Comment by mxmlnkn** [comment]
Fixed in 989b191b790018b6f4e685f34765964ad962886b
