### ISSUE TITLE
Nondeterministic "zran_read returned error (-3)"

### ISSUE THREAD

**Issue by epicfaace** [mxmlnkn/ratarmount#55]
I seem to be nondeterministically receiving "zran_read returned error (-3)" errors.

Full traceback:

```
Traceback (most recent call last):
  File "/Users/epicfaace/codalab/codalab-worksheets/tests/unit/server/upload_download_test.py", line 93, in test_bundle_folder
    bundle, [("item.txt", b"hello world"), ("src/item2.txt", b"hello world")]
  File "/Users/epicfaace/codalab/codalab-worksheets/tests/unit/server/upload_download_test.py", line 217, in upload_folder
    use_azure_blob_beta=True,
  File "/Users/epicfaace/codalab/codalab-worksheets/codalab/lib/upload_manager.py", line 162, in upload_to_bundle_store
    indexFileName=tmp_index_file.name,
  File "/Users/epicfaace/codalab/codalab-worksheets/codalab/lib/beam/ratarmount.py", line 450, in __init__
    self._createIndex(self.tarFileObject)
  File "/Users/epicfaace/codalab/codalab-worksheets/codalab/lib/beam/ratarmount.py", line 741, in _createIndex
    encoding     = self.encoding,
  File "/Users/epicfaace/.pyenv/versions/3.6.10/lib/python3.6/tarfile.py", line 1601, in open
    t = cls(name, filemode, stream, **kwargs)
  File "/Users/epicfaace/.pyenv/versions/3.6.10/lib/python3.6/tarfile.py", line 1482, in __init__
    self.firstmember = self.next()
  File "/Users/epicfaace/.pyenv/versions/3.6.10/lib/python3.6/tarfile.py", line 2297, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/Users/epicfaace/.pyenv/versions/3.6.10/lib/python3.6/tarfile.py", line 1092, in fromtarfile
    buf = tarfile.fileobj.read(BLOCKSIZE)
  File "/Users/epicfaace/.pyenv/versions/3.6.10/lib/python3.6/tarfile.py", line 539, in read
    buf = self._read(size)
  File "/Users/epicfaace/.pyenv/versions/3.6.10/lib/python3.6/tarfile.py", line 547, in _read
    return self.__read(size)
  File "/Users/epicfaace/.pyenv/versions/3.6.10/lib/python3.6/tarfile.py", line 572, in __read
    buf = self.fileobj.read(self.bufsize)
  File "indexed_gzip/indexed_gzip.pyx", line 720, in indexed_gzip.indexed_gzip._IndexedGzipFile.readinto
indexed_gzip.indexed_gzip.ZranError: zran_read returned error (-3)
```

I'll post more details as I get them.

**Comment by mxmlnkn** [comment]
This seems to be an indexed_gzip internal issue. Please try to reproduce the error without ratarmount and open an issue [there](https://github.com/pauldmccarthy/indexed_gzip/issues).
The error code itself [seems to](https://github.com/pauldmccarthy/indexed_gzip/blob/master/indexed_gzip/zran.h#L284) indicate a read error. Unfortunately, this error is returned for [multiple different](https://github.com/pauldmccarthy/indexed_gzip/blob/master/indexed_gzip/zran.c#L2155) internal errors, so I can't say what exactly went wrong.
