### ISSUE TITLE
Multiple simultaneous mounts

### ISSUE THREAD

**Issue by Vadiml1024** [mxmlnkn/ratarmount#83]
I'm working on a project where we need to simultaneously  mount a LOT of archives and I'm talking about thousands of them.
For the moment while experimenting with ratarmount we launch separate instance of ratarmount for each archive.
This generates ENORMOUS memory pressure on the system (especially when ratarmount distributed as AppImage because each invocation has seprate nonshared instance of python interpreter)
So we are considering to add an option to to read a file containing pairs:
"_filename_" "_mountpoint_"  
and have single instance of ratarmount create all **FuseMount** objects for them.

Do you have any feedback on this idea?

**Comment by mxmlnkn** [comment]
I'm not even sure whether FUSE and/or fusepy allows such as setup but I didn't try. For the mount point, it forks off a background process that keeps running. Maybe it works to do that multiple times but I kinda doubt it.

You could use union mounting (if each archive has a top-level directory) or recursive mounting for that, or are there problems?

In the worst case, if you really want specific mount point locations, you could use symbolic links like this:

```
# Create two archives at random positions
tar1=$( mktemp --suffix=.tar )
tar2=$( mktemp --suffix=.tar )
sample=$( mktemp )
echo foo > "$sample"
tar -cf "$tar1" "$sample"
tar -cf "$tar2" "$sample"
# Create an intermediary structure to mount both of them
folder=$( mktemp -d )
# Unfortunately, recursive mounting does not follow symlinks, so use hardlinks. I'd almost categorize this as a bug.
ln "$tar1" "$folder/$( basename -- "$tar1" )"
ln "$tar2" "$folder/$( basename -- "$tar2" )"
# Mount recursively
ratarmount --recursive "$folder" mountpoint
# Create links for desired mountpoint locations
ln -s "mountpoint/$( basename -- "$tar1" )" mountpoint1
ln -s "mountpoint/$( basename -- "$tar2" )" mountpoint2
```

One problem I see with this is that there is no option to specify the recursion depth, but that seems easier to implement than the pair-wise parsing.

**Comment by Vadiml1024** [comment]
It is an interesting idea, but I'm afraid will not work in our case,
because the various archives (and directories) are residing on
different disks
so handling are nogo....
However it makes me think about another possibility -
*VirtualMountSource* class
which will serve the role of **$folder**  from your example....
Should be not too complicated to implement....
So ratarmount will receive (somehow) a list of filenames will create a
*VirtualMountSource* and populate it with the supplied filenames
and will create *FuseMount *with this *VirtualMountSource...*

**Comment by mxmlnkn** [comment]
> It is an interesting idea, but I'm afraid will not work in our case,
> because the various archives (and directories) are residing on
> different disks
> so handling are nogo....

I forgot to update the code and comment. Symbolic links and therefore multi-disk also works! The problem in my tests was that I created the test files without any extension, which makes the recursive mounting fail because it only looks at extensions first to avoid expensive "disk" or archive / decompressor accesses.

> However it makes me think about another possibility -
> *VirtualMountSource* class
> which will serve the role of **$folder**  from your example....
> Should be not too complicated to implement....
> So ratarmount will receive (somehow) a list of filenames will create a
> *VirtualMountSource* and populate it with the supplied filenames
> and will create *FuseMount *with this *VirtualMountSource...*

I think the UnionMounting feature is already very similar. You can do:
    
```bash
ratarmount foo1.tar foo2.tar foo3.tar mountpoint
```

But this will mount the contents of each archive into the mountpoint. To be more generic, you would want to many the contents of each archive under a different folder under the mountpoint. I think that should be doable and I would prefer this to a new pairwise command line syntax.

**Comment by mxmlnkn** [comment]
> This generates ENORMOUS memory pressure on the system (especially when ratarmount distributed as AppImage because each invocation has seprate nonshared instance of python interpreter)

Are you sure the only problem is the Python interpreter binary? I assume your hands are bound to use that AppImage :/

One other thing I can think of might be the SQLite cache size. There currently is no option for that but as you have already forked, you can add it yourself inside `SQLiteIndexedTar._openSqlDb`: [`PRAGMA CACHE_SIZE 16`](https://blog.devart.com/increasing-sqlite-performance.html) and maybe repeat for the `PAGE_CACHE_SIZE`. But if #85 is responsible for the memory usage, then this might also not help much.

**Comment by Vadiml1024** [comment]
>Are you sure the only problem is the Python interpreter binary? I assume your hands are bound to use that AppImage :/

Actually, You are right,  I can't be sure about it, it was simply the first thing that came to mind as I saw the machine brought to its knees with a 1.5K ratarmount instances running.  

Now seeing you mentioning CACHE_SIZE and PAGE_CACHE size brings me to understand why I've seen (and continue to see even with single instance of ratarmount) the 160G of virtual memory usage on 16G machine.
These are probably zero-filled pages without physical memory backing, preallocated by SQLite.

**Comment by mxmlnkn** [comment]
I'm not sure whether you are still interested. I have to ideas for realizing something like that:

 1. `--disable-union-mount` or maybe `--mount-in-subfolders`. This option would simply mount each archive in an identically named subfolder. I guess that it does not scale up if there are multiple archives with the same name.
 2. `--batch-mount <file>`. Each line in the given file would be a set of arguments just as if calling ratarmount. All given mountpoints are limited to the actual mount point subfolder.

Example for 2:

```bash
# Create a.zip containing foo.txt
# Create /tmp/b.zip containing bar.txt
ratarmount --batch-mount <<HEREDOC all-mounted
--recursive a.zip mounted-a
b.zip mounted-b
a.zip b.zip union-mounted
HEREDOC
tree all-mounted
```

Expected output:

```
all-mounted
+- mounted-a
   +- foo.txt
+- mounted-b
   +- bar.txt
+- union-mounted
   +- foo.txt
   +- bar.txt
```

The `--recursive` in the first line is only to exemplify that in the ideal case all mount-relevant options can be specified per submount. Of course some command line arguments are not applicable for these submounts, I'll have to make a list of applicable options.

**Comment by Vadiml1024** [comment]
Sure, It will be pretty useful in our use case

**Comment by mxmlnkn** [comment]
3.  Same as 2 but, instead of specifying a file, each `--` in the command line would start a new submount.

# Same example for 3

`ratarmount all-mounted --recursive a.zip mounted-a -- b.zip mounted-b -- a.zip b.zip union-mounted`

Normally `--` is used to stop command line argument parsing and take all remaining arguments verbatim. I'm not sure whether I use that or need that. If there is an archive starting with `--` it could also be specified as `./--archive-name.zip` instead. Or alternatively, I could use `---` to separate submounts. So something like this would work:

`ratarmount all-mounted --recursive a.zip mounted-a --- --recursive -- --b.zip mounted-b --- a.zip b.zip union-mounted`

**Comment by Vadiml1024** [comment]
Outer mount folder location:  --target mountpoint

**Comment by mxmlnkn** [comment]
4. `ratarmount --batch-mount-listen`. Instead of specifying a single file, ratarmount can be used like a server. The format would be the same as proposed for the files but (zero-delimited) lines can be piped to ratarmount after the startup / after the mount point has been created. This also includes lines for unmounting. My first idea was communication via stdin but it might be more conventional to use a socket, which I have not much experience of using. Or maybe something like named pipes? 

    ```bash
    ratarmount --batch-mount-listen special-file all-mounted
    echo "a.zip mounted-a" >> special-file
    echo "--unmount mounted-a" >> special-file
    ...
    ```

**Comment by Vadiml1024** [comment]
Great idea

**Comment by mxmlnkn** [comment]
[ratarmount-manylinux2014_x86_64.AppImage.zip](https://github.com/mxmlnkn/ratarmount/files/10798146/ratarmount-manylinux2014_x86_64.AppImage.zip)

For now, I have implemented the simplest solution, the `--disable-union-mount`. I would be very interested if this actually reduces the memory usage you observed. The usage would be:

```bash
ratarmount-manylinux2014_x86_64.AppImage --disable-union-mount denormal-paths.zip large.zip mountPoint
tree mountPoint
```

Possible output:

```
mountPoint/
├── denormal-paths.zip
│   ├── foo
│   ├── root
│   │   └── bar
│   └── ufo
└── large.zip
    └── 10k-1MiB-files.tar.gz

3 directories, 4 files
```

**Comment by WizzardSK** [comment]
Hi, I tried that with 2 file stored on web server and after mount when I want to list ratarmount.mounted folder, I get this error:

Uncaught exception from FUSE operation readdir, returning errno.EINVAL.
Traceback (most recent call last):
  File "/tmp/.mount_ratarmoGofiH/opt/python3.12/lib/python3.12/site-packages/ratarmountcore/fusepy/fuse.py", line 1093, in _wrapper
    return func(*args, **kwargs) or 0
           ^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.mount_ratarmoGofiH/opt/python3.12/lib/python3.12/site-packages/ratarmountcore/fusepy/fuse.py", line 1398, in readdir
    return self._readdir(path, buf, filler, offset, fip)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.mount_ratarmoGofiH/opt/python3.12/lib/python3.12/site-packages/ratarmountcore/fusepy/fuse.py", line 1383, in _readdir
    setattr(st, 'st_mode', attrs['st_mode'])
TypeError: 'FileInfo' object cannot be interpreted as an integer
ls: reading directory '.': Invalid argument

**Comment by WizzardSK** [comment]
```
./ratarmount --version
ratarmount 1.0.0
ratarmountcore 0.8.0

System Software:

Python 3.12.7
FUSE 2.9.7
libsqlite3 3.46.1

Compression Backends:

PySquashfsImage 0.9.0
fast_zip_decryption 3.0.0
indexed_gzip 1.8.7
indexed_zstd 1.1.3
isal 1.7.1
libarchive 5.1
lz4 4.0.2
pyfatfs 1.2.0
pygit2 1.16.0
python-lzo 1.15
rapidgzip 0.14.3
rarfile 4.2
xz 0.4.0
zstandard 0.23.0

Fsspec Backends:

aiobotocore 2.15.2
aiohttp 3.10.10
asyncssh 2.18.0
cryptography 43.0.3
dag-cbor 0.3.3
dropbox 12.0.2
dropboxdrivefs 1.4.1
fsspec 2024.10.0
httpx 0.27.2
ipfsspec 0.5.3
multiformats 0.3.1
pure-protobuf 2.3.0
pyopenssl 24.2.1
pyspnego 0.11.1
python-dateutil 2.9.0.post0
requests 2.32.3
s3fs 2024.10.0
smbprotocol 1.14.0
sshfs 2024.9.0
webdav4 0.10.0

Versioned Loaded Shared Libraries:

libzstd-8d126cbb.so.1.5.5
libcrypto-efb7ea77.so.3
libgit2-822bb88b.so.1.8.1
libpcre-9513aab5.so.1.2.0
libssh2-c5cb4cb9.so.1.0.1
libssl-107481d2.so.3
libacl.so.1
libarchive.so.13.3.3
libattr.so.1
libbz2.so.1
libcrypto.so.1.1.1k
libffi.so.6
libfuse.so.2.9.7
liblz4.so.1
liblzma.so.5
libsqlite3.so.0
libssl.so.1.1
libxml2.so.2
libzstd.so.1
ld-linux-x86-64.so.2
libc.so.6
libdl.so.2
libgcc_s.so.1
libm.so.6
libnettle.so.8.8
libpthread.so.0
librt.so.1
libstdc++.so.6.0.33
libutil.so.1
libuuid.so.1.3.0
libz.so.1.3
```

this is the command I am running: 

` ./ratarmount --disable-union-mount https://www.atarimania.com/roms/Atari-2600-VCS-ROM-Collection.zip https://myrient.erista.me/files/TOSEC/Nintendo/64/Games/Nintendo%2064%20-%20Games.zip mount -f &`

My goal is to mount a lot of zip files directly from internet. I am able to mount those files separatelly. Testing it in WSL now,

**Comment by WizzardSK** [comment]
ok, I tried, but I am getting this error:

```
pip install -U ratarmountcore
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.

    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.

    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.

    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```

**Comment by mxmlnkn** [comment]
How did you install ratarmount in the first place? You should use the same method to update it. E.g., did you install it in a virtual environment? Are you using the AppImage, then ... ugh, I forgot to upload a newer AppImage release.

**Comment by mxmlnkn** [comment]
You can download a newer AppImage version [here](https://productionresultssa18.blob.core.windows.net/actions-results/c107f853-0fbd-4bdc-b43c-61c4bb7637f1/workflow-job-run-0a8e3e3d-5635-53d0-a15a-afb115070fff/artifacts/622ad9d2367e8bfc2ee7fd59e43fc40bde3a7174f84f177e3c1419570aa77ba2.zip?rscd=attachment%3B+filename%3D%22ratarmount-x86_64.AppImage.zip%22&se=2025-06-10T09%3A10%3A27Z&sig=ILZxsMWt1xMngrOARxKtppwh%2Fu56G8kWazeZLyH%2FFbU%3D&ske=2025-06-10T20%3A16%3A59Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2025-06-10T08%3A16%3A59Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2025-05-05&sp=r&spr=https&sr=b&st=2025-06-10T09%3A00%3A22Z&sv=2025-05-05) directly from the CI

**Comment by mxmlnkn** [comment]
> Ok, just one question. Is it possible to mount github repo recursivelly with subfolders?

What do you mean by subfolders? Subfolders are part of the repo and are shown when mounting the repo, e.g., with:

```
ratarmount -f github://mxmlnkn:ratarmount@v0.15.2/tests/ mounted
```

If you want to recursively mount archives in that repo as subfolders, you can do:

```
ratarmount -r -f github://mxmlnkn:ratarmount@v0.15.2/tests/ mounted
```

Although I would not recommend it for that example because it will try to mount hundreds of my test archives.

**Comment by mxmlnkn** [comment]
> There is just one small bug for http mounts. It writes "None" instead of actual file name.

Hm, this is kind of normal. This happens because the ZIP archives are mounted via HTTP. Python opens a file object for the ZIP behind the http:// URL and then gives it to the ZIP processing, which now has no name for that archive and therefore prints "None". I think the TAR backend is written slightly better and would print "Creating offset dictionary for <file object> ...". I probably should centralize that logic.

> btw, those parameters `-o kernel_cache,negative_timeout=60,entry_timeout=60` can be used with ratarmount?

Yes, the `-o` or `--fuse` option to ratarmount passes everything on to libfuse. These options are not implemented in ratarmount itself.

**Comment by mxmlnkn** [comment]
>> `[Warning] Failed to tear down root mount source because of: 'str' object has no attribute '__exit__'`
>
> I'll also have to look into that [Warning]. It looks like a bug.

This should be fixed in 4cd4fb63a17fa7e4df221c84c0bb53c826652766.


> This generates ENORMOUS memory pressure on the system (especially when ratarmount distributed as AppImage because each invocation has seprate nonshared instance of python interpreter)

I don't see this mentioned yet: I think this should have been preventable for AppImage by extracting the AppImage with `ratarmount.AppImage --extract-appimage` and then executing `squashfs-root/AppRun`. This also avoids the startup overhead and lots of FUSE mounts for the AppImage itself.

---

As for the original issue from more than 3 years ago :(, I have added a `--control-interface` option. You can now do fun stuff such as this:

```bash
mkdir mounted
./ratarmount-1.1.1-slim-x86_64.AppImage --control-interface mounted
# Arguments have to be absolute paths because the daemon process runs in `/` and cannot know
# the current working directory of the `echo` call.
echo "ratarmount -d 3 $PWD/tests/single-file.tar $HOME/mounted" > mounted/.ratarmount-control/command
sleep 1
cat mounted/.ratarmount-control/output
```

This starts new ratarmount subprocesses and creates new FUSE mounts. But, hopefully, the binaries at least can share their mmaped binaries and therefore reduce memory usage.

You can even do insane stuff like this:

```bash
mkdir mounted
./ratarmount-1.1.1-slim-x86_64.AppImage --control-interface mounted
# The mount point can be relative to mount into the existing FUSE mount!
echo "ratarmount -d 3 $PWD/tests/single-file.tar inner-mount" > mounted/.ratarmount-control/command
sleep 1
cat mounted/.ratarmount-control/inner-mount/bar
echo "ratarmount -u inner-mount" > mounted/.ratarmount-control/command
```

This should implement the original feature request completely. The logic to implement all that is slightly cursed at parts. But it also necessitated some other refactors and edge case testing, which probably improved the code base as a whole. It only works with `--disable-union-mount` or like shown above when only specifying the mount point because it needs some `SubvolumesMountSource`, which now supports dynamic `mount` and `unmount` methods.

Here is an AppImage (slim version without support for more exotic archive formats) for testing if anyone is still interested. Feedback would be welcome.

[ratarmount-slim-x86_64.AppImage.zip](https://github.com/user-attachments/files/21539946/ratarmount-slim-x86_64.AppImage.zip)
